---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: istio
  namespace: istio-system
  #annotations:
    #kubernetes.io/ingress.global-static-ip-name: staging-test
spec:
  backend:
      serviceName: istio-ingressgateway
      servicePort: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: health-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  annotations:
  name: health
  namespace: istio-system
spec:
  gateways:
  - health-gateway
  hosts:
  - '*'
  http:
  - match:
    - headers:
        user-agent:
          prefix: GoogleHC
      method:
        exact: GET
      uri:
        exact: /
    rewrite:
      authority: istio-ingressgateway.istio-system.svc.cluster.local:15020
      uri: /healthz/ready
    route:
    - destination:
        host: istio-ingressgateway.istio-system.svc.cluster.local
        port:
          number: 15020
